# Generated by Django 6.0.4 on 2026-04-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('game_name', models.CharField(max_length=255, verbose_name='Название игры')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Жанр')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('status', models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Игровая статья',
                'verbose_name_plural': 'Игровые статьи',
                'ordering': ['-time_create'],
                'indexes': [models.Index(fields=['-time_create'], name='arcada_game_time_cr_5fad07_idx'), models.Index(fields=['status'], name='arcada_game_status_b29e43_idx')],
            },
        ),
    ]
