# Generated by Django 6.0.4 on 2026-05-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamearticle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Черновик'), (1, 'Опубликовано'), (2, 'На модерации')], default=0, verbose_name='Статус'),
        ),
    ]
