# Generated by Django 6.0.4 on 2026-05-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcada', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
