# Generated by Django 6.0.4 on 2026-05-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcada', '0004_alter_tagpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
