# Generated by Django 6.0.4 on 2026-05-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arcada', '0006_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamearticle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='games/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
